@startuml table

class Root
class Header
class Router
class Footer

class TableMult
class PageTableMult


Root --> Header
Root --> Router
Root --> Footer
Router --> PageTableMult
Router --> PageTablesDesMult

PageTableMult -->"1  " TableMult
PageTablesDesMult -->"1..*  " TableMult

hide circle
hide method
@enduml
